log_sources:
  - ./logs
  - s3://my-bucket/logs/
match_keys:
  - transaction_id
output:
  format: html
  path: ./output
  max_files: 100
  max_size_mb: 10
verifier_endpoints:
  service_a: http://localhost:8000/verify
security:
  encrypt_logs: false