name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -e .[dev,kafka,aws,gcs,datadog]

    - name: Run tests with coverage
      run: |
        mkdir -p coverage
        pytest tests/ --cov=pipetracker --cov-report=xml:coverage/coverage.xml

    - name: List coverage file
      run: ls -lh coverage/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage/coverage.xml
        fail_ci_if_error: false   # workflow won’t fail if upload fails
        verbose: true
